name: 'Kubernetes deployment GKE'
author: 'Ruben'
description: 'github vulnerability check'
inputs:
  image:
    description: 'Docker image'
    required: true
  project:

branding:
  icon: 'package'
  color: 'red'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
